# Generated by Django 5.0.6 on 2024-07-09 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='todo_list',
            new_name='TodoList',
        ),
        migrations.AlterModelOptions(
            name='todolist',
            options={'ordering': ['time_create']},
        ),
    ]
